S=str(input("Dati sirul de caractere :"))
z=S.count('A')
print("Numarul de aparitii ale caracterului A este :",z)
sir=S.replace('A','*')
print("Sirul obtinut prin subtituirea caracterului A :",sir)
sir1=S.replace('B','')
print("Sirul obtinut prin radierea din sirul S a caracterului B :",sir1)
x=S.count('MA')
print("Numarul de aparitiiale silabei MA :", x )
sir2=S.replace('MA','TA') 
print("Sirul obtinut prin substituirea silabei MA :",sir2)
sir3=S.replace('TO','')
print("Sirul obtinut prin radierea silabei TO :",sir3)
sir4=S[::-1]
print("Sirul scris invers :", sir4)